import { normalizePropertyRow } from "@/src/lib/property-config";

export const apartmentImages = {
  facade: "/brand/hero-ra.png",
  towers: "/brand/apartments-hero-ra.png",
  living: "/apartments/sala-ra.png",
  kitchen: "/apartments/cozinha-ra.png",
  balcony: "/apartments/varanda-ra.png",
};

const mockRows = [
  { id: "residencial-aurora", codigo: "RA-101", titulo: "Residencial Aurora", tipo: "apartamento", status_obra: "lancamento", status: "disponivel", preco: 685000, cep: "", endereco: "Endereço sob consulta", bairro: "Centro", cidade: "Sua cidade", estado: "", descricao: "Plantas inteligentes de 2 e 3 quartos, varanda integrada e áreas comuns pensadas para uma rotina mais leve.", especificacoes: { area_m2: 82, quartos: 3, suites: 1, banheiros: 2, vagas: 2, previsao_entrega: "Sob consulta" }, area: 82, quartos: 3, banheiros: 2, vagas: 2, imagens: [apartmentImages.facade, apartmentImages.living, apartmentImages.kitchen], videos: [], destaque: true, criado_em: "2026-08-15T12:00:00Z" },
  { id: "essenza-residence", codigo: "RA-102", titulo: "Essenza Residence", tipo: "apartamento", status_obra: "em_construcao", status: "disponivel", preco: 520000, cep: "", endereco: "Endereço sob consulta", bairro: "Jardins", cidade: "Sua cidade", estado: "", descricao: "Apartamentos contemporâneos com ambientes integrados, conforto acústico e acabamento cuidadosamente selecionado.", especificacoes: { area_m2: 68, quartos: 2, suites: 1, banheiros: 2, vagas: 1, previsao_entrega: "Sob consulta" }, area: 68, quartos: 2, banheiros: 2, vagas: 1, imagens: [apartmentImages.towers, apartmentImages.kitchen, apartmentImages.balcony], videos: [], destaque: true, criado_em: "2026-08-10T12:00:00Z" },
  { id: "vista-cobre", codigo: "RA-103", titulo: "Vista Cobre", tipo: "apartamento", status_obra: "pronto_para_morar", status: "disponivel", preco: 890000, cep: "", endereco: "Endereço sob consulta", bairro: "Horizonte", cidade: "Sua cidade", estado: "", descricao: "Apartamento pronto para morar, com vista ampla, varanda gourmet e uma área social desenhada para receber bem.", especificacoes: { area_m2: 110, quartos: 3, suites: 2, banheiros: 3, vagas: 2, andar: 8 }, area: 110, quartos: 3, banheiros: 3, vagas: 2, imagens: [apartmentImages.balcony, apartmentImages.living, apartmentImages.facade], videos: [], destaque: true, criado_em: "2026-08-01T12:00:00Z" },
  { id: "linea-compact", codigo: "RA-104", titulo: "Linea Compact", tipo: "apartamento", status_obra: "lancamento", status: "disponivel", preco: 345000, cep: "", endereco: "Endereço sob consulta", bairro: "Estação", cidade: "Sua cidade", estado: "", descricao: "Unidades compactas com aproveitamento inteligente, ideais para a primeira compra ou para investimento.", especificacoes: { area_m2: 48, quartos: 1, banheiros: 1, vagas: 1 }, area: 48, quartos: 1, banheiros: 1, vagas: 1, imagens: [apartmentImages.towers, apartmentImages.kitchen], videos: [], destaque: false, criado_em: "2026-07-20T12:00:00Z" },
  { id: "reserva-urban", codigo: "RA-105", titulo: "Reserva Urban", tipo: "apartamento", status_obra: "em_construcao", status: "disponivel", preco: 740000, cep: "", endereco: "Endereço sob consulta", bairro: "Reserva", cidade: "Sua cidade", estado: "", descricao: "Três quartos, lazer completo e paisagismo que aproxima natureza e vida urbana.", especificacoes: { area_m2: 94, quartos: 3, suites: 1, banheiros: 2, vagas: 2 }, area: 94, quartos: 3, banheiros: 2, vagas: 2, imagens: [apartmentImages.facade, apartmentImages.balcony, apartmentImages.living], videos: [], destaque: false, criado_em: "2026-07-10T12:00:00Z" },
  { id: "studio-ra", codigo: "RA-106", titulo: "Studio R & A", tipo: "apartamento", status_obra: "pronto_para_morar", status: "disponivel", preco: 298000, cep: "", endereco: "Endereço sob consulta", bairro: "Centro", cidade: "Sua cidade", estado: "", descricao: "Studio pronto para morar, com serviços compartilhados e localização conectada à rotina da cidade.", especificacoes: { area_m2: 36, quartos: 1, banheiros: 1, vagas: 0, andar: 6 }, area: 36, quartos: 1, banheiros: 1, vagas: 0, imagens: [apartmentImages.living, apartmentImages.kitchen], videos: [], destaque: false, criado_em: "2026-06-28T12:00:00Z" },
];

export const mockProperties = mockRows.map((property) => normalizePropertyRow(property));
